@startuml

actor Admin
actor Employee

Admin --> (Login)
Admin --> (Manage Employees)
Admin --> (Calculate Payroll)
Admin --> (Manage Salary)
Admin --> (Lock Entries)
Admin --> (Generate Reports)
Admin --> (Search)

Employee --> (Login)
Employee --> (Enter hours or PTO)
Employee --> (View Paycheck)

@enduml
